### PR TITLE
Changes in the playlist ui

### PR DESCRIPTION
**Pull request by Ssionn**
CleanShot 2024-09-16 at 21 54 34@2x

### CODE REVIEW

**Comment by Ssionn** [comment]
CleanShot 2024-09-16 at 23 18 57@2x

**Comment by nonbots** [comment]
LNGTM! What happened to the arrow for pages?

**Comment by Ssionn** [comment]
MERGE IT

**Comment by nonbots** [comment]
Alright! Let's try it!

**Pull request merged**
