### PR TITLE
Delete public/assets/icons/arrow.svg:Zone.Identifier, playlist buttons cursor pointer, fixed size and align song card edit/delete buttons

### LINKED ISSUE #17: erroneous file, cause invalid file path error on Windows
https://github.com/nonbots/nhanify/blob/7d460caa60f9c68e29339db20c98d43bbb90e3dc/public/assets/icons/arrow.svg%3AZone.Identifier#L1

> error: invalid path 'public/assets/icons/arrow.svg:Zone.Identifier'

### PR DESCRIPTION
**Pull request by tuanthien**
delete file to fix #17

### CODE REVIEW

**Comment by tuanthien** [comment]
if you want the entire song card is the click-to-play area, i could change that.

**Review by nonbots — COMMENTED** [review]
Already been deleted!

**Review by nonbots — COMMENTED** [review]
LGTME!

**Review by nonbots — COMMENTED** [review]
Ok!

**Pull request merged**
